config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pics#index'
  resources :pics do
    member do
      put "like", to: "pics#upvote"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @pics = Pic.all.order("created_at DESC")
  end

  def new
    @pic = current_user.pics.build
  end

  def create
    @pic = current_user.pics.build(pic_params)

    if @pic.save
      redirect_to @pic, notice: "Yes! It was posted!"
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: "Congrats! Pic was updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end

  def upvote
    @pic.upvote_by current_user
    render :show
  end

  private
  def pic_params
    params.require(:pic).permit(:title, :description, :image)
  end

  def find_pic 
    @pic = Pic.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSocialMedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav navbar navbar-inverse">
      <div class="container">
          <%= link_to  "PhotoNetwork", root_path, class: "navbar-brand" %>
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to  "Gram It!", new_pic_path %></li>
              <li><%= link_to  "Settings", edit_user_registration_path %></li>
              <li><%= link_to  "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to  "Join", new_user_registration_path %></li>
              <li><%= link_to  "Log In", new_user_session_path %></li>
            </ul>
          <% end %>
      </div>
    </div>

    <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info"  %>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pics/_form.html.erb
<%= simple_form_for @pic, html: { multipart: true } do |f| %>
  <% if @pic.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@pic.errors.count, "error") %>
        Erro!
      </h2>
      <ul>
        <% @pic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :image, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.button :submit, input_html: { class: 'form-control btn btn-info' } %>
  </div>

<% end %>

app/views/pics/edit.html.erb
<div id="edit_page" class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Fix Pic</h1>
      </div>
      
      <div class="panel-body">
        <div class=".current_image">
          <strong class="center"> Right now  </strong> <br>
          <%= image_tag @pic.image.url(:medium) %>
        </div>
        <%= render  "form" %>
        <%= link_to  "Back", root_path %>
      </div>
    </div>
  </div>
</div>

app/views/pics/index.html.erb
<div class="col-md-12">
  <div id="pics" class="transitions-enabled">
      <% @pics.each do |pic| %>
      <div class="box panel panel-default">
          <%= link_to (image_tag pic.image.url), pic %>
          <h2>
            <%= link_to pic.title, pic  %>
          </h2>
      </div>
    <% end %>
  </div>
</div>

app/views/pics/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Post Pic</h1>
      </div>
      <div class="panel-body">
        <%= render  "form" %>
        <%= link_to  "Back", root_path %>
      </div>
    </div>
  </div>
</div>

app/views/pics/show.html.erb
<main id="pic_show" class="row">
  <section class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <header class="panel heading pic_image">
        <%= image_tag @pic.image.url %>
      </header>
      <div class="panel-body">
        <h1><%= @pic.title %></h1>
        <p><%= @pic.description %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">
              By <%= @pic.user.email %>
            </p>
          </div>
         
          <div class="btn-group pull-right">
            <% if user_signed_in? %>
            <%= link_to like_pic_path(@pic), method: :put, class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-thumbs-up">
              <%= @pic.get_upvotes.size %>
            </span>
            <% end %>
              <%= link_to  "Edit", edit_pic_path, class: "btn btn-info" %>
              <%= link_to  "Delete", pic_path, method: :delete, data: { confirm: "Are u sure?"}, class: "btn btn-danger" %>
            <% end %>
          </div>
        </div> 
      </div>
    </div>
  </section>
</main>